### ISSUE TITLE
Monster's Not Displaying in Initiative Tracker

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [MostTornBrain/monster-mash#2]
In the process of making a video for this, I noticed that the monsters do not work with Initiative Tracker when using the Parse from Notes option. 

Very hard to see, but the error is actually a rogue space on the bottom of the monster statblocks. 
Once the additional space is removed, the statblock renders perfectly in Initiative Tracker. 

Confirmed this impacts both Weak and Elite monsters. 

<SPACE>```

![image](https://github.com/MostTornBrain/monster-mash/assets/96321415/1b76bc00-ec19-4d52-887f-187f5c533890)

**Comment by MostTornBrain** [comment]
I believe this is fixed in the latest version.  If it is not, please let me know and I'll reopen this issue.
